class ListMotivation {
  static List<String> motivationalQuotes = [
    "Jika Anda dapat memimpikannya, Anda dapat melakukannya.",
    "Kegagalan adalah kesempatan untuk memulai lagi dengan lebih bijaksana.",
    "Bermimpilah yang tinggi, carilah yang tak terjangkau.",
    "Keberhasilan dimulai dengan keputusan untuk mencoba.",
    "Kesuksesan terbesar terletak pada kemampuan untuk bangkit setelah jatuh.",
    "Hanya mereka yang berani gagal secara besar-besaran yang mampu meraih kesuksesan secara besar-besaran.",
    "Ketika pikiran Anda berpikir positif, kesempatan akan muncul.",
    "Bekerja keras adalah kunci kesuksesan.",
    "Jangan menyerah, keajaiban bisa terjadi hanya dalam sekejap.",
    "Berpikirlah positif, dan hal-hal positif akan terjadi.",
    "Sesuatu yang hebat tidak pernah mudah.",
    "Ketika Anda mengubah cara Anda melihat sesuatu, sesuatu yang Anda lihat pun berubah.",
    "Jangan pernah menyerah, karena setelah hujan selalu ada pelangi.",
    "Lakukan yang terbaik dan biarkan Tuhan yang melakukan sisanya.",
    "Kesuksesan adalah hasil dari kegigihan, ketekunan, dan belajar dari kegagalan.",
    "Kemauan kuat adalah kunci untuk mencapai apa pun yang Anda impikan.",
    "Tetaplah berpegang pada impianmu, karena ketika ada kehendak, ada jalan.",
    "Jadilah yang terbaik dalam hal apa pun yang Anda lakukan.",
    "Setiap hari adalah kesempatan baru untuk mencapai sesuatu yang luar biasa.",
    "Hidup adalah perjalanan yang indah, jangan sia-siakan setiap detiknya.",
    "Keberanian adalah saat Anda berhenti memikirkan dan mulai melakukannya.",
    "Kesuksesan adalah hasil dari mimpi besar, kerja keras, dan ketekunan.",
    "Jangan takut gagal, karena kegagalan adalah langkah menuju kesuksesan.",
    "Tidak ada kata terlambat untuk memulai. Waktu yang tepat adalah sekarang.",
    "Percaya pada diri sendiri adalah kunci kesuksesan.",
    "Keinginan untuk berhasil harus lebih besar daripada ketakutan akan kegagalan.",
    "Anda adalah penentu dari kesuksesan Anda sendiri.",
    "Kesuksesan bukanlah kunci kebahagiaan. Kebahagiaan adalah kunci kesuksesan.",
    "Ketika Anda berhenti bermimpi, Anda berhenti hidup.",
    "Lakukan hari ini apa yang orang lain tidak bersedia lakukan, untuk memiliki besok apa yang orang lain tidak dapat miliki.",
    "Jangan biarkan kesulitan menghentikan Anda. Biarkan itu menjadi pendorong Anda untuk mencapai kesuksesan.",
    "Ketika Anda berpikir bahwa Anda tidak dapat melakukannya, ingatlah mengapa Anda mulai melakukannya.",
    "Kesuksesan bukanlah akhir dari perjalanan. Itu adalah awal dari petualangan baru.",
    "Percayalah pada diri Anda sendiri dan segala hal menjadi mungkin.",
    "Setiap langkah kecil membawa Anda lebih dekat ke tujuan Anda.",
    "Sesuatu yang besar selalu dimulai dengan langkah-langkah kecil.",
    "Jangan biarkan impian menjadi sekadar mimpi. Jadikan impian itu kenyataan.",
    "Hidup tidak pernah memberi Anda lebih dari apa yang Anda mampu tangani.",
    "Percayalah pada proses. Satu hari semuanya akan berharga.",
    "Keberanian tidak selalu berteriak. Kadang-kadang, itu adalah suara kecil yang mengatakan, 'Saya akan mencoba lagi besok.'",
    "Hidup adalah anugerah, jadilah berkat bagi orang lain.",
    "Jika Anda bisa mengimajinasikannya, Anda bisa mencapainya.",
    "Kesuksesan adalah menerima kegagalan dengan semangat yang berbeda.",
    "Berkat datang kepada mereka yang bangun setiap pagi mencari cara untuk memberikan nilai kepada orang lain.",
    "Rahasia kesuksesan adalah memulai sebelum Anda merasa siap.",
    "Kebahagiaan bukanlah tujuan, tetapi cara hidup.",
    "Hidup adalah petualangan yang harus dinikmati.",
    "Ketika Anda berfokus pada kebaikan, kebaikan lebih banyak datang dalam hidup Anda.",
    "Kesuksesan adalah hasil dari kegigihan, keberanian, dan keberanian untuk mencoba lagi.",
    "Jangan pernah meremehkan kekuatan kata-kata positif. Mereka mampu mengubah hidup.",
    "Teruslah melangkah maju. Setiap langkah membawa Anda lebih dekat ke tujuan Anda.",
    "Keberhasilan tidak terjadi secara kebetulan. Itu adalah hasil dari kerja keras dan ketekunan.",
    "Ketika hidup memberimu seratus alasan untuk menangis, tunjukkan pada hidup bahwa Anda memiliki seribu alasan untuk tersenyum.",
    "Hidup adalah tentang menciptakan diri Anda sendiri.",
    "Tidak ada gunanya membandingkan diri Anda dengan orang lain. Setiap orang adalah unik dan memiliki perjalanan mereka sendiri.",
    "Kesempatan biasanya terlihat seperti kerja keras, jadi sebagian besar orang tidak mengenalinya.",
    "Mimpi besar adalah langkah pertama untuk mencapai sesuatu yang luar biasa.",
    "Jangan pernah menyerah pada mimpi Anda. Dunia membutuhkan orang-orang yang berani bermimpi besar.",
    "Hidup adalah apa yang Anda buat. Jadi, buatlah itu luar biasa.",
    "Jangan biarkan masa lalu yang menyedihkan menghentikan masa depan yang indah.",
    "Setiap hari adalah kesempatan baru untuk menjadi lebih baik dari hari sebelumnya.",
    "Tetaplah fokus pada tujuan Anda. Sulit bukan berarti tidak mungkin.",
    "Kesuksesan bukanlah akhir dari perjalanan. Itu adalah langkah pertama menuju perjalanan yang lebih besar.",
    "Anda memiliki kekuatan untuk mengubah hidup Anda. Gunakan dengan bijaksana.",
    "Kesempatan datang dengan cara yang tidak terduga. Jadi, siapkan diri Anda untuk mengambilnya.",
    "Ketika Anda berhenti bermimpi, Anda berhenti hidup. Jadi, teruslah bermimpi.",
    "Kesuksesan adalah hasil dari mimpi besar, kerja keras, dan tekad yang kuat.",
    "Setiap hari adalah kesempatan baru untuk menjadi versi terbaik dari diri Anda sendiri.",
    "Kesuksesan bukanlah tujuan akhir, itu adalah perjalanan yang terus berlanjut.",
    "Hidup adalah apa yang Anda perbuat. Jadi, lakukanlah dengan baik.",
    "Jika Anda tidak mengambil langkah, Anda akan selalu berada di tempat yang sama.",
    "Bersyukur untuk apa yang Anda miliki saat ini dan kerja keraslah untuk apa yang ingin Anda capai.",
    "Percaya pada diri sendiri adalah kunci kesuksesan. Jika Anda tidak percaya pada diri sendiri, siapa lagi yang akan?",
    "Tidak ada batasan bagi apa yang dapat Anda capai jika Anda percaya pada diri sendiri.",
    "Jadilah yang terbaik dalam hal apa pun yang Anda lakukan, karena itu adalah penanda Anda.",
    "Pikirkan besar, impikan besar, dan kerjakan dengan sungguh-sungguh.",
    "Ketika Anda merasa lelah, ingatlah mengapa Anda memulainya.",
    "Anda tidak pernah terlalu tua untuk mengatur tujuan baru atau bermimpi yang baru.",
    "Jangan takut gagal, takutlah tidak pernah mencoba.",
    "Hidup adalah tentang membuat perbedaan dalam hidup orang lain.",
    "Jangan biarkan orang lain menghentikan Anda dari mengejar impian Anda. Hanya Anda yang tahu apa yang Anda mampu.",
    "Kesuksesan adalah hasil dari kegigihan, keyakinan, dan kerja keras yang tak kenal lelah.",
    "Hidup adalah tentang menciptakan diri Anda sendiri. Jadi, jadilah versi terbaik dari diri Anda.",
    "Tidak ada keberhasilan tanpa kegagalan. Jadi, jadilah berani untuk gagal dan belajar darinya.",
    "Impian Anda tidak akan menjadi kenyataan jika Anda tidak mengambil tindakan.",
    "Jika Anda ingin mengubah hidup Anda, Anda harus mulai dengan mengubah pikiran Anda.",
    "Ketika kehidupan memberi Anda seratus alasan untuk menyerah, tunjukkan padanya seribu alasan untuk bertahan.",
    "Tetaplah berpegang pada mimpi Anda. Mereka adalah kunci untuk mencapai apa pun yang Anda inginkan.",
    "Kesuksesan tidak diberikan. Itu diperoleh melalui kerja keras, ketekunan, dan dedikasi.",
    "Hidup adalah tentang menjalani petualangan dan menemukan makna dalam setiap langkahnya.",
    "Jika Anda tidak pernah mencoba, Anda tidak akan pernah tahu apa yang bisa Anda capai.",
    "Pikirkan positif, lakukan positif, dan hasilnya akan menjadi positif.",
    "Hidup ini singkat. Jangan sia-siakan waktu Anda dengan hal-hal yang tidak penting.",
    "Keberhasilan datang kepada mereka yang bersedia melakukan apa yang orang lain tidak bersedia lakukan.",
    "Jadilah seseorang yang menginspirasi orang lain untuk berbuat lebih baik.",
    "Anda adalah penulis dari cerita hidup Anda sendiri. Jadi, buatlah cerita yang luar biasa.",
    "Hidup adalah tentang menciptakan momen yang tak terlupakan.",
    "Jangan biarkan rintangan menghentikan Anda. Jadikan itu tantangan yang harus Anda taklukkan.",
    "Ketika Anda berhenti bermimpi, Anda berhenti hidup. Jadi, teruslah bermimpi dan bergerak maju.",
    "Setiap langkah kecil membawa Anda lebih dekat ke tujuan Anda. Jadi, teruslah melangkah maju.",
    "Hidup adalah tentang perjalanan, bukan tujuan akhir.",
    "Kesuksesan adalah hasil dari ketekunan, ketabahan, dan tekad yang kuat.",
    "Berhenti memikirkan kemungkinan kegagalan dan mulailah berpikir tentang peluang keberhasilan.",
    "Percayalah pada diri sendiri dan segala sesuatu akan mungkin.",
    "Hidup adalah tentang menjalani setiap hari dengan niat yang baik dan hati yang tulus.",
    "Kegagalan bukan akhir dari cerita. Itu adalah bagian dari perjalanan menuju kesuksesan.",
    "Hidup adalah tentang memberi makna pada setiap momen yang kita miliki.",
    "Jangan menunggu kesempurnaan sebelum Anda bertindak. Ambillah langkah pertama sekarang.",
    "Hidup adalah tentang menemukan diri Anda sendiri dan menjadi yang terbaik dari diri Anda.",
    "Kesuksesan adalah hasil dari keputusan kecil yang kita buat setiap hari.",
    "Jadilah yang terbaik dalam hal apa pun yang Anda lakukan, dan orang lain akan mengikuti contoh Anda.",
    "Hidup adalah tentang memberikan lebih dari yang Anda terima.",
    "Jika Anda tidak pernah mencoba, Anda tidak akan pernah tahu seberapa jauh Anda bisa pergi.",
    "Jadilah terang yang menerangi dunia di sekitar Anda.",
    "Setiap langkah yang Anda ambil hari ini membawa Anda lebih dekat ke impian Anda.",
    "Anda memiliki kekuatan untuk mencapai apa pun yang Anda impikan. Percayalah pada diri sendiri.",
    "Ketika Anda merasa putus asa, ingatlah mengapa Anda memulainya.",
    "Hidup adalah tentang menghargai setiap momen yang kita miliki. Jangan sia-siakan waktu Anda dengan hal-hal yang tidak penting.",
    "Bersyukurlah untuk apa yang Anda miliki saat ini dan bekerja keras untuk apa yang ingin Anda capai.",
    "Jangan pernah menyerah pada impian Anda. Dunia membutuhkan orang-orang yang berani bermimpi besar.",
    "Hidup adalah apa yang Anda buat. Jadi, buatlah itu luar biasa.",
    "Setiap langkah kecil membawa Anda lebih dekat ke tujuan Anda. Jadi, teruslah maju.",
    "Jadilah yang terbaik dalam hal apa pun yang Anda lakukan. Itu adalah penanda Anda.",
    "Ketika Anda merasa lelah, ingatlah mengapa Anda memulainya.",
    "Anda tidak pernah terlalu tua untuk menetapkan tujuan baru atau bermimpi yang baru.",
    "Jangan takut gagal. Gagal adalah langkah menuju kesuksesan.",
    "Hidup adalah tentang membuat perbedaan dalam hidup orang lain.",
    "Jangan biarkan orang lain menghentikan Anda dari mengejar impian Anda. Hanya Anda yang tahu apa yang Anda mampu.",
    "Kesuksesan adalah hasil dari kerja keras, ketekunan, dan keyakinan pada diri sendiri.",
    "Hidup adalah tentang menciptakan diri Anda sendiri. Jadi, jadilah versi terbaik dari diri Anda.",
    "Tidak ada batasan bagi apa yang dapat Anda capai jika Anda percaya pada diri sendiri.",
    "Jadilah seseorang yang menginspirasi orang lain dengan tindakan dan kata-kata Anda.",
    "Jadilah positif dalam pikiran, kata-kata, dan tindakan Anda. Itu akan mempengaruhi hidup Anda dan orang-orang di sekitar Anda.",
    "Jangan menunggu kesempurnaan sebelum Anda bertindak. Mulailah dari mana pun Anda berada, dengan apa yang Anda miliki.",
    "Kesuksesan tidak diberikan, itu diperoleh melalui kerja keras, ketekunan, dan dedikasi.",
    "Hidup adalah tentang menjalani petualangan dan menemukan makna di dalamnya.",
    "Jika Anda ingin mengubah hidup Anda, Anda harus mulai dengan mengubah pikiran Anda.",
    "Percayalah pada diri sendiri dan segala sesuatu akan mungkin.",
    "Hidup ini singkat. Jangan sia-siakan waktu Anda dengan hal-hal yang tidak penting.",
    "Jangan biarkan rintangan menghentikan Anda. Jadikan itu tantangan yang harus Anda taklukkan.",
    "Ketika Anda berhenti bermimpi, Anda berhenti hidup. Jadi, teruslah bermimpi dan bergerak maju.",
    "Setiap langkah kecil membawa Anda lebih dekat ke tujuan Anda. Jadi, teruslah melangkah maju.",
    "Hidup adalah tentang perjalanan, bukan tujuan akhir.",
    "Kesuksesan adalah hasil dari ketekunan, ketabahan, dan tekad yang kuat.",
    "Berhenti memikirkan kemungkinan kegagalan dan mulailah berpikir tentang peluang keberhasilan.",
    "Percayalah pada diri sendiri dan segala sesuatu akan mungkin.",
    "Hidup adalah tentang menjalani setiap hari dengan niat yang baik dan hati yang tulus.",
    "Kegagalan bukan akhir dari cerita. Itu adalah bagian dari perjalanan menuju kesuksesan.",
    "Hidup adalah tentang memberikan lebih dari yang Anda terima.",
    "Jika Anda tidak pernah mencoba, Anda tidak akan pernah tahu seberapa jauh Anda bisa pergi.",
    "Jadilah terang yang menerangi dunia di sekitar Anda.",
    "Setiap langkah yang Anda ambil hari ini membawa Anda lebih dekat ke impian Anda.",
    "Anda memiliki kekuatan untuk mencapai apa pun yang Anda impikan. Percayalah pada diri sendiri.",
    "Ketika Anda merasa putus asa, ingatlah mengapa Anda memulainya.",
    "Hidup adalah tentang menghargai setiap momen yang kita miliki. Jangan sia-siakan waktu Anda dengan hal-hal yang tidak penting.",
    "Bersyukurlah untuk apa yang Anda miliki saat ini dan bekerja keras untuk apa yang ingin Anda capai.",
    "Jangan pernah menyerah pada impian Anda. Dunia membutuhkan orang-orang yang berani bermimpi besar.",
    "Hidup adalah apa yang Anda buat. Jadi, buatlah itu luar biasa.",
    "Setiap langkah kecil membawa Anda lebih dekat ke tujuan Anda. Jadi, teruslah maju.",
    "Jadilah yang terbaik dalam hal apa pun yang Anda lakukan. Itu adalah penanda Anda.",
    "Ketika Anda merasa lelah, ingatlah mengapa Anda memulainya.",
    "Anda tidak pernah terlalu tua untuk menetapkan tujuan baru atau bermimpi yang baru.",
    "Jangan takut gagal. Gagal adalah langkah menuju kesuksesan.",
    "Hidup adalah tentang membuat perbedaan dalam hidup orang lain.",
    "Jangan biarkan orang lain menghentikan Anda dari mengejar impian Anda. Hanya Anda yang tahu apa yang Anda mampu.",
    "Kesuksesan adalah hasil dari kerja keras, ketekunan, dan keyakinan pada diri sendiri.",
    "Hidup adalah tentang menciptakan diri Anda sendiri. Jadi, jadilah versi terbaik dari diri Anda.",
    "Tidak ada batasan bagi apa yang dapat Anda capai jika Anda percaya pada diri sendiri.",
    "Jadilah seseorang yang menginspirasi orang lain dengan tindakan dan kata-kata Anda.",
    "Jadilah positif dalam pikiran, kata-kata, dan tindakan Anda. Itu akan mempengaruhi hidup Anda dan orang-orang di sekitar Anda.",
    "Jangan menunggu kesempurnaan sebelum Anda bertindak. Mulailah dari mana pun Anda berada, dengan apa yang Anda miliki.",
    "Kesuksesan tidak diberikan, itu diperoleh melalui kerja keras, ketekunan, dan dedikasi.",
    "Hidup adalah tentang menjalani petualangan dan menemukan makna di dalamnya.",
    "Jika Anda ingin mengubah hidup Anda, Anda harus mulai dengan mengubah pikiran Anda.",
    "Percayalah pada diri sendiri dan segala sesuatu akan mungkin.",
    "Hidup ini singkat. Jangan sia-siakan waktu Anda dengan hal-hal yang tidak penting.",
    "Jangan biarkan rintangan menghentikan Anda. Jadikan itu tantangan yang harus Anda taklukkan.",
    "Ketika Anda berhenti bermimpi, Anda berhenti hidup. Jadi, teruslah bermimpi dan bergerak maju.",
    "Setiap langkah kecil membawa Anda lebih dekat ke tujuan Anda. Jadi, teruslah melangkah maju.",
    "Hidup adalah tentang perjalanan, bukan tujuan akhir.",
    "Kesuksesan adalah hasil dari ketekunan, ketabahan, dan tekad yang kuat.",
    "Berhenti memikirkan kemungkinan kegagalan dan mulailah berpikir tentang peluang keberhasilan.",
    "Percayalah pada diri sendiri dan segala sesuatu akan mungkin.",
    "Hidup adalah tentang menjalani setiap hari dengan niat yang baik dan hati yang tulus.",
    "Kegagalan bukan akhir dari cerita. Itu adalah bagian dari perjalanan menuju kesuksesan.",
    "Hidup adalah tentang memberikan lebih dari yang Anda terima.",
    "Jika Anda tidak pernah mencoba, Anda tidak akan pernah tahu seberapa jauh Anda bisa pergi.",
    "Jadilah terang yang menerangi dunia di sekitar Anda.",
    "Setiap langkah yang Anda ambil hari ini membawa Anda lebih dekat ke impian Anda.",
    "Anda memiliki kekuatan untuk mencapai apa pun yang Anda impikan. Percayalah pada diri sendiri.",
    "Ketika Anda merasa putus asa, ingatlah mengapa Anda memulainya.",
    "Hidup adalah tentang menghargai setiap momen yang kita miliki. Jangan sia-siakan waktu Anda dengan hal-hal yang tidak penting.",
    "Bersyukurlah untuk apa yang Anda miliki saat ini dan bekerja keras untuk apa yang ingin Anda capai.",
    "Jangan pernah menyerah pada impian Anda. Dunia membutuhkan orang-orang yang berani bermimpi besar.",
    "Hidup adalah apa yang Anda buat. Jadi, buatlah itu luar biasa.",
    "Setiap langkah kecil membawa Anda lebih dekat ke tujuan Anda. Jadi, teruslah maju.",
    "Jadilah yang terbaik dalam hal apa pun yang Anda lakukan. Itu adalah penanda Anda.",
    "Ketika Anda merasa lelah, ingatlah mengapa Anda memulainya.",
    "Anda tidak pernah terlalu tua untuk menetapkan tujuan baru atau bermimpi yang baru.",
    "Jangan takut gagal. Gagal adalah langkah menuju kesuksesan.",
    "Hidup adalah tentang membuat perbedaan dalam hidup orang lain.",
    "Jangan biarkan orang lain menghentikan Anda dari mengejar impian Anda. Hanya Anda yang tahu apa yang Anda mampu.",
    "Kesuksesan adalah hasil dari kerja keras, ketekunan, dan keyakinan pada diri sendiri.",
    "Hidup adalah tentang menciptakan diri Anda sendiri. Jadi, jadilah versi terbaik dari diri Anda.",
    "Tidak ada batasan bagi apa yang dapat Anda capai jika Anda percaya pada diri sendiri.",
    "Jadilah seseorang yang menginspirasi orang lain dengan tindakan dan kata-kata Anda.",
    "Jadilah positif dalam pikiran, kata-kata, dan tindakan Anda. Itu akan mempengaruhi hidup Anda dan orang-orang di sekitar Anda.",
    "Jangan menunggu kesempurnaan sebelum Anda bertindak. Mulailah dari mana pun Anda berada, dengan apa yang Anda miliki.",
    "Kesuksesan tidak diberikan, itu diperoleh melalui kerja keras, ketekunan, dan dedikasi.",
    "Hidup adalah tentang menjalani petualangan dan menemukan makna di dalamnya.",
    "Jika Anda ingin mengubah hidup Anda, Anda harus mulai dengan mengubah pikiran Anda.",
    "Percayalah pada diri sendiri dan segala sesuatu akan mungkin.",
    "Hidup ini singkat. Jangan sia-siakan waktu Anda dengan hal-hal yang tidak penting.",
    "Jangan biarkan rintangan menghentikan Anda. Jadikan itu tantangan yang harus Anda taklukkan.",
    "Ketika Anda berhenti bermimpi, Anda berhenti hidup. Jadi, teruslah bermimpi dan bergerak maju.",
    "Setiap langkah kecil membawa Anda lebih dekat ke tujuan Anda. Jadi, teruslah melangkah maju.",
    "Hidup adalah tentang perjalanan, bukan tujuan akhir.",
    "Kesuksesan adalah hasil dari ketekunan, ketabahan, dan tekad yang kuat.",
    "Berhenti memikirkan kemungkinan kegagalan dan mulailah berpikir tentang peluang keberhasilan.",
    "Percayalah pada diri sendiri dan segala sesuatu akan mungkin.",
    "Hidup adalah tentang menjalani setiap hari dengan niat yang baik dan hati yang tulus.",
    "Kegagalan bukan akhir dari cerita. Itu adalah bagian dari perjalanan menuju kesuksesan.",
    "Hidup adalah tentang memberikan lebih dari yang Anda terima.",
    "Jika Anda tidak pernah mencoba, Anda tidak akan pernah tahu seberapa jauh Anda bisa pergi.",
    "Jadilah terang yang menerangi dunia di sekitar Anda.",
    "Setiap langkah yang Anda ambil hari ini membawa Anda lebih dekat ke impian Anda.",
    "Anda memiliki kekuatan untuk mencapai apa pun yang Anda impikan. Percayalah pada diri sendiri.",
    "Ketika Anda merasa putus asa, ingatlah mengapa Anda memulainya.",
    "Hidup adalah tentang menghargai setiap momen yang kita miliki. Jangan sia-siakan waktu Anda dengan hal-hal yang tidak penting.",
    "Bersyukurlah untuk apa yang Anda miliki saat ini dan bekerja keras untuk apa yang ingin Anda capai.",
    "Jangan pernah menyerah pada impian Anda. Dunia membutuhkan orang-orang yang berani bermimpi besar.",
    "Hidup adalah apa yang Anda buat. Jadi, buatlah itu luar biasa.",
    "Setiap langkah kecil membawa Anda lebih dekat ke tujuan Anda. Jadi, teruslah maju.",
    "Jadilah yang terbaik dalam hal apa pun yang Anda lakukan. Itu adalah penanda Anda.",
    "Ketika Anda merasa lelah, ingatlah mengapa Anda memulainya.",
    "Anda tidak pernah terlalu tua untuk menetapkan tujuan baru atau bermimpi yang baru.",
    "Jangan takut gagal. Gagal adalah langkah menuju kesuksesan.",
    "Hidup adalah tentang membuat perbedaan dalam hidup orang lain.",
    "Jangan biarkan orang lain menghentikan Anda dari mengejar impian Anda. Hanya Anda yang tahu apa yang Anda mampu.",
    "Kesuksesan adalah hasil dari kerja keras, ketekunan, dan keyakinan pada diri sendiri.",
    "Hidup adalah tentang menciptakan diri Anda sendiri. Jadi, jadilah versi terbaik dari diri Anda.",
    "Tidak ada batasan bagi apa yang dapat Anda capai jika Anda percaya pada diri sendiri.",
    "Jadilah seseorang yang menginspirasi orang lain dengan tindakan dan kata-kata Anda.",
    "Jadilah positif dalam pikiran, kata-kata, dan tindakan Anda. Itu akan mempengaruhi hidup Anda dan orang-orang di sekitar Anda.",
    "Jangan menunggu kesempurnaan sebelum Anda bertindak. Mulailah dari mana pun Anda berada, dengan apa yang Anda miliki.",
    "Kesuksesan tidak diberikan, itu diperoleh melalui kerja keras, ketekunan, dan dedikasi.",
    "Hidup adalah tentang menjalani petualangan dan menemukan makna di dalamnya.",
    "Jika Anda ingin mengubah hidup Anda, Anda harus mulai dengan mengubah pikiran Anda.",
    "Percayalah pada diri sendiri dan segala sesuatu akan mungkin.",
    "Hidup ini singkat. Jangan sia-siakan waktu Anda dengan hal-hal yang tidak penting.",
    "Jangan biarkan rintangan menghentikan Anda. Jadikan itu tantangan yang harus Anda taklukkan.",
    "Ketika Anda berhenti bermimpi, Anda berhenti hidup. Jadi, teruslah bermimpi dan bergerak maju.",
    "Setiap langkah kecil membawa Anda lebih dekat ke tujuan Anda. Jadi, teruslah melangkah maju.",
    "Hidup adalah tentang perjalanan, bukan tujuan akhir.",
    "Kesuksesan adalah hasil dari ketekunan, ketabahan, dan tekad yang kuat.",
    "Berhenti memikirkan kemungkinan kegagalan dan mulailah berpikir tentang peluang keberhasilan.",
    "Percayalah pada diri sendiri dan segala sesuatu akan mungkin.",
    "Hidup adalah tentang menjalani setiap hari dengan niat yang baik dan hati yang tulus.",
    "Kegagalan bukan akhir dari cerita. Itu adalah bagian dari perjalanan menuju kesuksesan.",
    "Hidup adalah tentang memberikan lebih dari yang Anda terima.",
    "Jika Anda tidak pernah mencoba, Anda tidak akan pernah tahu seberapa jauh Anda bisa pergi.",
    "Jadilah terang yang menerangi dunia di sekitar Anda.",
    "Setiap langkah yang Anda ambil hari ini membawa Anda lebih dekat ke impian Anda.",
    "Anda memiliki kekuatan untuk mencapai apa pun yang Anda impikan. Percayalah"
  ];
}